### ISSUE TITLE
Exit code is always 0

### ISSUE THREAD

**Issue by just-boris** [glenjamin/mocha-multi#11]
Given a simple setup:
```
multi="progress=-" mocha --reporter mocha-multi
```
Always return zero exit code, even tests has been failed. Library versions:
```
   "mocha": "2.3.2",
   "mocha-multi": "0.7.1",
```

I guess it happens because visionmedia/mocha#1059 already merged and some hacks doesn't necessary anymore. I could remove them by myself, but I am not sure, which parts of hacks actually still needed.

**Comment by just-boris** [comment]
Also see my commit https://github.com/just-boris/mocha-multi/commit/a0756d77db695e311b2674f8629a412ec04d10b1 as possible fix

**Comment by glenjamin** [comment]
`// Wait for streams, then exit` seems redundant as a comment now you've extracted the function neatly.

Aside from that the change looks fine to me - can you make a pull request for it?
