### ISSUE TITLE
How to add xml report in grunt

### ISSUE THREAD

**Issue by DeChrish** [glenjamin/mocha-multi#17]
Need example:

**Comment by glenjamin** [comment]
What do you have so far? What isn't working?

**Comment by DeChrish** [comment]
Currently i am using the below code,

var config = {
mochaTest: {}
};
config.mochaTest[name] = {
options: {
reporter: 'mocha-allure-reporter',
reporterOptions: {
targetDir: allureReportFolderName
},
timeout: 60000,
logErrors: true,
captureFile: directories.target + '/' + name + '/test-results.txt'
},
src: grunt.option("mochatestspecs").split(",")
};

**Comment by glenjamin** [comment]
You should be able to use something like this https://github.com/glenjamin/mocha-multi#using-mocha-multi-programmatically

```js
reporter: "mocha-multi",
reporterOptions: {
  "mocha-allure-reporter": {
    options: { "targetDir": allureReportFolderName }
  }
  "xml": {
  // ...
  }
}
```

**Comment by DeChrish** [comment]
how to use other reprter, example i need BOTH allure reporter and tap reporter:

**Comment by glenjamin** [comment]
that example looks right to me, each key in the reporterOptions names another reporter to use.

**Comment by DeChrish** [comment]
Error : 
Running "mochaTest:endtoend" (mochaTest) task
>> Mocha exploded!
>> TypeError: path must be a string
>>     at TypeError (native)
>>     at Object.fs.openSync (fs.js:584:18)****

**Comment by glenjamin** [comment]
Sounds like you need to pass a filename to one of your reporters using its reporter options - as it doesn't write to stdout the file handling code from this lib won't affect its destination.

**Comment by DeChrish** [comment]
can you explain ?

**Comment by glenjamin** [comment]
I can see nothing obviously wrong with that, although it looks like you're only actually doing one output format, so `mocha-multi` isn't really doing anything useful for you there.

Is that stack trace you provided the full one, it would be helpful to know exactly what was passed to that `openSync` call which failed.

**Comment by DeChrish** [comment]
```javascript
Running "mochaTest:endtoend" (mochaTest) task
>> Mocha exploded!
>> TypeError: path must be a string
>>     at TypeError (native)
>>     at Object.fs.openSync (fs.js:584:18)
>>     at Object.fs.writeFileSync (fs.js:1224:33)
>>     at resolveStream (/../node_modules/mocha-multi/mocha-multi.js:162:6)
>>     at /../node_modules/mocha-multi/mocha-multi.js:91:18
>>     at Array.map (native)
>>     at initReportersAndStreams (/../node_modules/mocha-multi/mocha-multi.js:86:16)
>>     at new MochaMulti (/../node_modules/mocha-multi/mocha-multi.js:42:17)
>>     at MochaWrapper.run (/../node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:56:27)
>>     at /../node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
Warning: Task "mochaTest:endtoend" failed. Use --force to continue.

Aborted due to warnings.
Generating Allure Report at location './allure-reports'...
allure generate allure-results-firefox/
cp: allure-results-firefox: No such file or directory
ERROR: Report directory <allure-results-firefox/> is missing.
./runtestsuite: line 9: /../allure-commandline/bin/allure.bat: No such file or directory
```

**Comment by glenjamin** [comment]
Ah ok, you have to specify a target for the reporter being passed to `multi`, even though `allure` won't use it:

Try this
```js
                "mocha-allure-reporter": {
                    stdout: "-",
                    options: { "targetDir": allureReportFolderName }
                }
```

**Comment by DeChrish** [comment]
@glenjamin Like a Boss 👏 👏 👏

**Comment by DeChrish** [comment]
Hey quick info : 
```javascript
"mocha-allure-reporter": {
                    stdout: "-",
                    options: { "targetDir": allureReportFolderName }
                }
```

targetDir is not working,
the reports is generated in one particular location: it dont care about the path we are providing ;allureReportFolderName;

**Comment by glenjamin** [comment]
That looks like a bug in `mocha-allure-reporter`, I think this line https://github.com/allure-framework/mocha-allure-reporter/blob/master/index.js#L18 should just be `opts`.

You can work around it for now by doing:

```js
"mocha-allure-reporter": {
    stdout: "-",
    options: {
        reporterOptions: {
            "targetDir": allureReportFolderName
        }
    }
}
```
