### ISSUE TITLE
Cannot direct a reporter to console out when programatically using protractor

### ISSUE THREAD

**Issue by bloatedsack** [glenjamin/mocha-multi#19]
I'm trying to drive reporter options programmatically through grunt. 

This works fine:
```
var mochaMultiReporterOptions = {
		xunit: {
			stdout: 'build-artifacts/reporters/results.xml'
		},
		json: {
			stdout: 'build-artifacts/reporters/json-reporter.json'
		}
};
```

But when I try to direct something to console I get a protractor error. The code:
```
var mochaMultiReporterOptions = {
	xunit: {
		stdout: 'build-artifacts/reporters/results.xml'
	},
	json: {
		stdout: 'build-artifacts/reporters/json-reporter.json'
	},
	spec:  '-'
};
```

The error:
"Error: more than one config file specified"

Versions:
    "grunt-protractor-runner": "~2.0",
    "grunt-protractor-webdriver": "~0.2",
    "mocha": "~2.4",
    "mocha-multi": "^0.9.0",
    "protractor": "~2.5",

Mocha options:
```
{
	ui: 'bdd',
	reporter: 'mocha-multi',
	timeout: '540000',
	reporterOptions: mochaMultiReporterOptions
};
```

Any ideas? 
Other things I have tried:
- double quotes around "-"
- including `stdout: '-'` as an option for `spec`

**Comment by glenjamin** [comment]
I've never seen that error before, do you know which module is producing it?

Can you get a stack trace, or grep for the phrases in your `node_modules` folder?

**Comment by bloatedsack** [comment]
Here's the line that's throwing:
https://github.com/angular/protractor/blob/2.5.1/lib/cli.js#L68 

And here's the string it's launcing with (I added some endlines so we can read it here):
```
Spawn node with arguments: node_modules/grunt-protractor-runner/node_modules/protractor/bin/protractor node_modules/testcore/src/conf/protractor.conf.js 
--seleniumAddress http://localhost:4444/wd/hub --baseUrl https://blahblah.com/ --browser chrome 
--specs workspace/tests/test/e2e/stories/**/*.js 
--verbose 
--mochaOpts.ui bdd 
--mochaOpts.reporter mocha-multi 
--mochaOpts.timeout 540000 
--mochaOpts.reporterOptions.xunit.stdout build-artifacts/reporters/results.xml 
--mochaOpts.reporterOptions.json.stdout build-artifacts/reporters/json-reporter.json 
--mochaOpts.reporterOptions.spec -
```

It seems to be that last `-`

So, here's how I fixed it `spec: '"-"'` 
/shrug :shipit: ?

**Comment by bloatedsack** [comment]
Nope, take it back. That didn't fix it. It creates a file named "-" and directs spec stdout to it.

**Comment by glenjamin** [comment]
Ah, so the problem is that something in the chain is doing an incorrect transformation of those options.

I don't know how protractor expands those arguments, so you'd have to look into how that happens. Perhaps doing `arg=val` for each one will stop the `-` getting lost.

**Comment by bloatedsack** [comment]
I'm not sure what you mean about setting `arg=val`. 

The version of protractor I'm on (2.5) uses the now deprecated [optimist](https://github.com/substack/node-optimist) for arg parsing. It's also going through the grunt layer, so who knows that's doing to the args as well.

After tinkering with a few more string manipulations I ended up working around it by driving it through the env var.

```
	process.env.multi = 'spec=- ' 
		+ 'xunit=build-artifacts/reporters/results.xml '
		+ 'json=build-artifacts/reporters/json-reporter.json';
```

**Comment by glenjamin** [comment]
it might have worked using `--mochaOpts.reporterOptions.spec=-`, but I forgot you don't get control over how that command string gets created.

Environment variable won't be going away, so should be pretty reliable.
