### ISSUE TITLE
Configuring two reporters from protractor conf.js

### ISSUE THREAD

**Issue by ghost** [glenjamin/mocha-multi#21]
Hi, I am trying to use two below two reporters and declare them into protractor.conf.js using 'mocha-multi'. I tried searching docs on how do that but in vain. I see most examples were around configurations from command line when running with mocha

I basically need to combine both these reports as I need both

Reporter 1:

mochaOpts: {
  ui: 'bdd',
  reporter: 'mochawesome-screenshots',
  reporterOptions: {
    reportDir: testResultsDir,
    reportName: 'TestExecutionReport',
    reportTitle: 'Sample Reports',
    takePassedScreenshot: true,
    clearOldScreenshots: true
  }
 }

Reporter 2:

  mochaOpts: {
    ui: 'bdd',
    reporter: mochaReporter,
    timeout: 20000,
    reporterOptions: {
      console: true,
      storyDir: testCasesDir,
      outputDir: testResultsDir
    }
  },

**Comment by glenjamin** [comment]
Assuming protractor does the right thing, you should be able to use the approach documented under https://github.com/glenjamin/mocha-multi#using-mocha-multi-programmatically to configure multiple reporterts using `reporterOptions`

**Comment by jhenaoz** [comment]
hi @glenjamin  , thanks for the comment, i am having the same issue but with custom reporters, can you provide and example for using this libr with one custom reporter?

**Comment by jhenaoz** [comment]
i make further research on that and protractor launch a procces for each capability (firefox, chrome) so it run the same test twice and the reports are overriden. @glenjamin
