### ISSUE TITLE
--reporter options and multiple options for reporter not supported

### ISSUE THREAD

**Issue by highvoltag3** [glenjamin/mocha-multi#22]
If you have a custom reporter like mochawesome which takes more than one option mocha-multi won't work since the options are separated by comma just like --reporter-options.

Example: 
`--reporter-options reportDir=customReportDir,reportName=customReportName` that's what mochawesome expects.
But passing that to mocha-multi would be something like:
`--reporter-options spec=-,mochawesome=reportDir=customReportDir,reportName=customReportName` notice how reportName would become another reporter in this case.

**Comment by glenjamin** [comment]
Yep, I can see how that would be a problem.

Any suggestions?

I seem to recall there's a way to pass reporter options as JSON, but I might have imagined that

**Comment by highvoltag3** [comment]
@glenjamin I don't think Mocha supports JSON in `--reporter-options` I have seen reporter options being passed as JSON on a different mocha-multi project [mocha-multi-reporters](https://github.com/stanleyhlng/mocha-multi-reporters)

**Comment by Glavin001** [comment]
Switching to [mocha-multi-reporters](mocha-multi-reporters) helped. Thank you for sharing, @highvoltag3!
