### ISSUE TITLE
make process.exit hack tidier

### ISSUE THREAD

**Issue by graingert** [glenjamin/mocha-multi#41]
Now that https://github.com/mochajs/mocha/pull/1059 is released the process.exit hack could be tidier

**Comment by graingert** [comment]
@glenjamin now that I look into this, I'm not actually sure how to do it.

**Comment by glenjamin** [comment]
I'm not really sure either anymore.

I think when I wrote that TODO it was before the code to wait for the streams to finish existed - now that this exists I'm not sure the monkeypatching can be removed

**Comment by graingert** [comment]
@glenjamin probably ready for a release then?
