### ISSUE TITLE
release 0.12.0

### ISSUE THREAD

**Issue by graingert** [glenjamin/mocha-multi#46]
@glenjamin any chance of a release?

**Comment by glenjamin** [comment]
Looking at the changes from the last version all together, the summary seems to be:

Expanded peerDependency range to include mocha 4, which required no changes
Made a bunch of backwards incompatible changes

I'm not clear anything has been gained by doing this from an end-user point-of-view.

Have I missed anything?

**Comment by graingert** [comment]
@glenjamin it won't print out an ugly peerDep warning.

**Comment by graingert** [comment]
@glenjamin also fixes:

> Support running mocha without a run callback

**Comment by graingert** [comment]
@glenjamin ping.

**Comment by glenjamin** [comment]
I've released `0.11.1` which contains the dependency bumps but none of the breaking changes.

Haven't yet decided where I stand on making the breaking changes.

**Comment by graingert** [comment]
@glenjamin FYI, semver supports breaking changes on any 0.x release.

**Comment by graingert** [comment]
but good choice on the 0.11.1 release

**Comment by glenjamin** [comment]
My main concern is how many users a release forces to make changes, and whether they get any benefit in exchange for that work.
