### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by nemanjacosovic** [glenjamin/mocha-multi#48]
After installing, a lot of dependency issues.

> npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> + multi-mocha@0.1.0

![screen-shot-2017-11-29-at-12 22 39-pm](https://user-images.githubusercontent.com/23336275/33373018-63cc5836-d500-11e7-9c57-c47f4e4a8a3b.jpg)

**Comment by glenjamin** [comment]
Did you install an up to date version of mocha first?

I don't think many of those are actually dependencies of this module - they might be pulled in by an old peerDepedency version

**Comment by nemanjacosovic** [comment]
Hi @glenjamin I'm running "mocha": "^4.0.1".

**Comment by glenjamin** [comment]
The problem here seems to be that you're installing `multi-mocha` instead of `mocha-multi` - didn't spot that before!
