### ISSUE TITLE
Release v1.0.1 to npm

### ISSUE THREAD

**Issue by irnnr** [glenjamin/mocha-multi#52]
Noticed v1.0.1 is tagged here, but not released to npm.

**Comment by shenghu** [comment]
Since 1.0.0 report warning w/ mocha 5.0.0, can 1.0.1 be pushed to npm asap? @glenjamin

**Comment by glenjamin** [comment]
Sorry for the delay, now published

**Comment by irnnr** [comment]
thanks so much!
