### ISSUE TITLE
mocha 6 support: process never ends (grunt)

### ISSUE THREAD

**Issue by senseysensor** [glenjamin/mocha-multi#55]
Currently here is an issue with mocha 6 (6.0.2): on tests completion process never stops. Even the only reporter (for example, `spec`) causes process forever freezing.

I run tests with grunt. My node version is 10.15.1.

**Comment by mikeharder** [comment]
This may have been fixed by #61.

**Comment by senseysensor** [comment]
yes, works for me now (mocha 6.2.0, mocha-multi 1.1.3). Great work.

**Comment by senseysensor** [comment]
Yes, works for me now! mocha 6.2.0, mocha-multi 1.1.3. Thank you for the fix.
