### ISSUE TITLE
Versions differ on npm and github

### ISSUE THREAD

**Issue by thiagodp** [glenjamin/mocha-multi#57]
Hello,
according to the [releases page](https://github.com/glenjamin/mocha-multi/releases), the latest version is `1.1.0`. However, [in NPM](https://www.npmjs.com/package/mocha-multi), the latest version is `1.0.1`.

Could you publish the latest version to NPM? Thanks

**Comment by glenjamin** [comment]
Whoops, good spot!

**Comment by glenjamin** [comment]
That's now published.

**Comment by thiagodp** [comment]
Thank you, @glenjamin !
