### ISSUE TITLE
Releases that tell the news

### ISSUE THREAD

**Issue by thiagodp** [glenjamin/mocha-multi#58]
It would be nice if mocha-multi's [releases](https://github.com/glenjamin/mocha-multi/releases) could tell what's new.

**Comment by glenjamin** [comment]
Releases are pretty rare these days, the commit log will have to suffice - I don't spend much time on maintainance.

If I ever have need to introduce a breaking change, I'll document that in the README.

**Comment by thiagodp** [comment]
Okay. Breaking changes could also increase the `major` version, [to make it explicit](https://semver.org/).

**Comment by glenjamin** [comment]
Yeah, i’d definitely inc the major, but i’d also document migration and what the breaking change was

**Comment by thiagodp** [comment]
Great. I just saw you did it when `1.0.0` was released. Thx
