### ISSUE TITLE
Latest version of mocha-v7.0.0 seems to be breaking mocha-multi

### ISSUE THREAD

**Issue by HarshaNalluru** [glenjamin/mocha-multi#68]
[mocha](https://github.com/mochajs/mocha/releases/tag/v7.0.0) recently had a release, version 7.0.0.
The current mocha-multi library can't seem to take in the changes from this latest version.

In a branch of my fork for the mocha-multi repo, updated the mocha version to 7.0.0  to verify - https://github.com/HarshaNalluru/mocha-multi/commit/3b6d5a50e2e668f4da3c4002a321c41397a3fb34

The tests seem to fail.

With `npm run test`..
```bash
> mocha-multi@1.1.3 test <path>/mocha-multi
> run-s lint verify:*


> mocha-multi@1.1.3 lint <path>/mocha-multi
> eslint . --max-warnings 0


> mocha-multi@1.1.3 verify:node <path>/mocha-multi
> node ./verify.js

ERROR: reporter definitions should be set in the `multi` shell variable
eg. `multi='dot=- xunit=file.xml' mocha`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mocha-multi@1.1.3 verify:node: `node ./verify.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mocha-multi@1.1.3 verify:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Comment by glenjamin** [comment]
If anyon has any insight into this issue, a PR would be appeciated.

**Comment by MarcCelani-at** [comment]
All the tests seem to pass on mocha 9, in case you still care.
