### ISSUE TITLE
npm ERR! peer dep missing: mocha@>=2.2.0 <7.0.0, required by mocha-multi@1.1.3

### ISSUE THREAD

**Issue by AlexShkunov** [glenjamin/mocha-multi#75]
Latest Mocha version as of today - 8.3.2
Please bump up the compatibility - we have dependency checker breaking if using latest mocha, however using 7.x is suboptimal

https://www.npmjs.com/package/mocha

**Comment by glenjamin** [comment]
Not sure when I'll get to this, but if someone would like to submit a PR that would be great

**Comment by brunoklein** [comment]
this combination worked for me:

```
"mocha": "8.4.0",
"mocha-multi": "^1.1.3"
```

*The mocha v9.0.0 has the same peer dep missing issue :(

**Comment by MarcCelani-at** [comment]
We have been using mocha multi with mocha 9 and it's working fine. Is there any reason we can't just update the peer dependency requirement?

**Comment by glenjamin** [comment]
As before, a PR from someone who has tested it would be great

**Comment by MarcCelani-at** [comment]
Cool, I'm going to send it. I haven't exhaustively tested it, but like I said, we haven't had any problems with it and would love to see our install logs cleaner.

**Comment by jhernandez287** [comment]
The same thing happens when you have mocha 10 , I open an issue but is gone, do you have a fix for this?
