### ISSUE TITLE
Update version of mkdirp

### ISSUE THREAD

**Issue by MarcCelani-at** [glenjamin/mocha-multi#84]
mocha-multi depends on an old version of mkdirp and I see this log line in my yarn install:
```
➤ YN0061: │ mkdirp@npm:0.5.1 is deprecated: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)


yarn why mkdirp
├─ mocha-multi@npm:1.1.5
│  └─ mkdirp@npm:0.5.5 (via npm:^0.5.1)
```

**Comment by glenjamin** [comment]
Eugh, deprecation warnings for packages which work fine are so annoying.

If someone would like to send in a PR I'll accept it

**Comment by MarcCelani-at** [comment]
Hey @glenjamin , happy new year. I sent a PR do you mind taking a look?

**Comment by graingert** [comment]
@glenjamin fyi all supported versions of node support mkdir recursive now https://nodejs.org/api/fs.html#fspromisesmkdirpath-options

**Comment by glenjamin** [comment]
Yeah, I'm pretty sure under the hood `mkdirp` will use that if available.

I have no idea what node versions people are using this with, so I'm not particularly motivated to drop the dep
