### ISSUE TITLE
Cannot resolved peer dep for mocha 10  , npm Err mocha@">=2.2.0 <7 || ^9" from mocha-multi@1.1.6 

### ISSUE THREAD

**Issue by jhernandez287** [glenjamin/mocha-multi#91]
I get the following error when trying to install mocha-multi 1.16 with mocha 10.0.0

Could not resolve dependency: npm WARN peer mocha@">=2.2.0 <7 || ^9" from mocha-multi@1.1.6 npm WARN node_modules/mocha-multi

Just want to know if you are aware of this issue, I haven't found out how to resolve this, here are my devdependencies

`  "devDependencies": {
    "chai": "^4.3.6",
    "eslint": "^8.21.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-es5": "^1.2.0",
    "eslint-config-es5": "^0.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-react": "^7.30.1",
    "mocha": "^10.0.0",
    "pkg": "^5.8.0"
  }`

Thanks a lot,

**Comment by glenjamin** [comment]
I've just released `v1.1.7` which relaxes the peerDependency range to now also allow any mocha version 9 or above

**Comment by jhernandez287** [comment]
Thanks :) a lot <3
